"""
File Organizer - turns extracted notebook data into clean folder structure
"""
import re, json
from pathlib import Path
from datetime import datetime
from rich.console import Console
console = Console()

UPLOAD_GUIDE_TEMPLATE = """# Upload Guide: {title}

## Step 1: Create a new Project
1. Go to claude.ai
2. Click Projects in the left sidebar
3. Click New Project
4. Name it: {title}

## Step 2: Add Project Instructions
1. Inside your new project, click Set Instructions
2. Open PROJECT_INSTRUCTIONS.md from this folder
3. Copy the entire contents and paste them in
4. Click Save

## Step 3: Upload your knowledge files
1. Click Add Content or the + button in the project
2. Upload ALL files from the sources/ folder
3. Also upload NOTES.md and KEY_OUTPUTS.md if they have content

## Step 4: Test it
Ask: "Summarise everything you know about this project based on the documents I've uploaded."

---
*Generated by NotebookLM to Claude Projects Migration Tool*
*Digital Renaissance | digital-renaissance.tech*
"""

NOTES_TEMPLATE = "# Notes: {title}\n\n*Exported from NotebookLM Studio*\n*{timestamp}*\n\n---\n\n{notes_content}\n"
OUTPUTS_TEMPLATE = "# Key Outputs: {title}\n\n*Saved chat responses from NotebookLM*\n*{timestamp}*\n\n---\n\n{outputs_content}\n"


class FileOrganizer:
    def __init__(self, output_path: Path):
        self.output_path = output_path

    def _sanitize_folder_name(self, name: str) -> str:
        safe = re.sub(r'[^\w\s-]', '', name)
        safe = re.sub(r'[\s-]+', '_', safe)
        return safe[:60].strip('_') or "Untitled_Notebook"

    def organize(self, extracted: dict) -> Path:
        title = extracted.get("title", "Untitled Notebook")
        folder_name = self._sanitize_folder_name(title)
        notebook_dir = self.output_path / folder_name
        sources_dir = notebook_dir / "sources"
        notebook_dir.mkdir(parents=True, exist_ok=True)
        sources_dir.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        notes = extracted.get("notes", [])
        notes_content = self._format_notes(notes) if notes else "_No notes found in this notebook._"
        (notebook_dir / "NOTES.md").write_text(NOTES_TEMPLATE.format(title=title, timestamp=timestamp, notes_content=notes_content), encoding="utf-8")
        messages = extracted.get("chat_messages", [])
        outputs_content = self._format_messages(messages) if messages else "_No chat history found._"
        (notebook_dir / "KEY_OUTPUTS.md").write_text(OUTPUTS_TEMPLATE.format(title=title, timestamp=timestamp, outputs_content=outputs_content), encoding="utf-8")
        (notebook_dir / "UPLOAD_GUIDE.md").write_text(UPLOAD_GUIDE_TEMPLATE.format(title=title), encoding="utf-8")
        sources = extracted.get("source_files", extracted.get("sources", []))
        for i, source in enumerate(sources):
            source_title = self._sanitize_folder_name(source.get("title", f"source_{i+1}"))
            source_type = source.get("type", "text")
            content = source.get("content", "")
            filename = f"{source_title}.pdf" if source_type == "pdf" else f"{source_title}.txt"
            source_path = sources_dir / filename
            if content:
                source_path.write_text(content, encoding="utf-8")
            else:
                placeholder = f"# Source: {source.get('title', 'Unknown')}\n\nType: {source_type}\n\n_Content could not be automatically extracted._\n\nPlease manually copy the content from NotebookLM and paste it here, or upload the original file directly to Claude Projects."
                source_path.with_suffix(".txt").write_text(placeholder, encoding="utf-8")
        sources_index = "# Sources Index\n\n" + "\n".join([f"- **{s.get('title','Unknown')}** ({s.get('type','unknown')})" for s in sources]) or "_No sources detected._\n"
        (sources_dir / "SOURCES_INDEX.md").write_text(sources_index, encoding="utf-8")
        log = {"title": title, "exported_at": timestamp, "source_count": len(sources), "note_count": len(notes), "chat_message_count": len(messages), "folder": str(notebook_dir)}
        (notebook_dir / "MIGRATION_LOG.json").write_text(json.dumps(log, indent=2), encoding="utf-8")
        return notebook_dir

    def save_instructions(self, title: str, instructions: str):
        folder_name = self._sanitize_folder_name(title)
        path = self.output_path / folder_name / "PROJECT_INSTRUCTIONS.md"
        path.write_text(instructions, encoding="utf-8")

    def save_template_instructions(self, title: str):
        from src.generators.project_instructions import get_template_instructions
        folder_name = self._sanitize_folder_name(title)
        path = self.output_path / folder_name / "PROJECT_INSTRUCTIONS.md"
        path.write_text(get_template_instructions(title), encoding="utf-8")

    def _format_notes(self, notes: list) -> str:
        if not notes: return "_No notes found._"
        return "\n\n---\n\n".join([f"## Note {i}\n\n{n.get('content', n.get('title', ''))}" for i, n in enumerate(notes, 1)])

    def _format_messages(self, messages: list) -> str:
        if not messages: return "_No chat history found._"
        lines = []
        for msg in messages:
            role = msg.get("role", "unknown").upper()
            content = msg.get("content", "")
            if role == "USER": lines.append(f"**You:** {content}\n")
            elif role == "ASSISTANT": lines.append(f"**NotebookLM:** {content}\n")
            else: lines.append(f"**{role}:** {content}\n")
        return "\n".join(lines)